(function(g){var window=this;var Bza=function(a,b){return g.Lb(a,b)},$5=function(a,b,c){a.A.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.E)()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.jn(a.A,b,c)},Cza=function(a,b){var c=[];
g.ok(b,function(d){try{var e=g.io.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.ho(e)&&c.push(d)},a);
return c},Dza=function(a,b){var c=Cza(a,b);
(0,g.y)(c,function(d){g.io.prototype.remove.call(this,d)},a)},Eza=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},Fza=function(a,b){g.gb(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},Gza=function(a,b){var c=b instanceof g.zc?b:g.Fc(b,/^data:image\//i.test(b));
a.src=g.Ac(c)},d6=function(){},Hza=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Iza=function(a){if(a.Ud&&"function"==typeof a.Ud)return a.Ud();
if("string"===typeof a)return a.split("");if(g.Oa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Hb(a)},Jza=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Oa(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.df&&"function"==typeof a.df)var c=a.df();else if(a.Ud&&"function"==typeof a.Ud)c=void 0;else if(g.Oa(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Ib(a);d=Iza(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Kza=function(a,b,c,d){var e=new g.Xm(null,void 0);
a&&g.Ym(e,a);b&&g.Zm(e,b);c&&g.$m(e,c);d&&(e.u=d);return e},e6=function(a,b){g.Qo[a]=!0;
var c=g.Oo();c&&c.publish.apply(c,arguments);g.Qo[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Um;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Lza(this,a.capabilities||""),Mza(this,a.experiments||""))},Lza=function(a,b){a.capabilities.clear();
(0,g.De)(b.split(","),g.Ta(Bza,Nza)).forEach(function(c){a.capabilities.add(c)})},Mza=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Oza=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Pza=function(a){return new g6(a)},Qza=function(a){return Array.isArray(a)?(0,g.Lc)(a,Pza):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+(0,g.Lc)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},Rza=function(a){return(0,g.Lc)(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.db(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.db(a,function(c){return h6(c,b)})},Sza=function(){var a=(0,g.Xs)();
a&&Dza(a,a.o.Uh(!0))},n6=function(){var a=g.$s("yt-remote-connected-devices")||[];
g.xb(a);return a},Tza=function(a){if(g.ib(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Lc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Uza=function(a){g.Zs("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.$s("yt-remote-device-id");a||(a=k6(),g.Zs("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.gb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.gb(a,b);g.bt()&&g.zb(a,b);a=Tza(a);if(g.ib(a))try{g.Bq.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.Cq("remote_sid",a.join(","),-1)}catch(c){}},Vza=function(){return g.$s("yt-remote-session-browser-channel")},Wza=function(){return g.$s("yt-remote-local-screens")||[]},Xza=function(){g.Zs("yt-remote-lounge-token-expiration",!0,86400)},Yza=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Lc)(Wza(),function(d){return d.loungeToken}),c=(0,g.Lc)(a,function(d){return d.loungeToken});
(0,g.Bi)(c,function(d){return!g.gb(b,d)})&&Xza();
g.Zs("yt-remote-local-screens",a,31536E3)},Zza=function(a,b){g.Zs("yt-remote-session-browser-channel",a);
g.Zs("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.gb(c,d)||c.push(d);Uza(c);q6()},r6=function(a){a||(g.at("yt-remote-session-screen-id"),g.at("yt-remote-session-video-id"));
q6();a=n6();g.lb(a,p6());Uza(a)},$za=function(){if(!s6){var a=g.oo();
a&&(s6=new g.Zn(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},aAa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},bAa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?cAa(a.shift(),function(){t6(a)}):u6()},dAa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},cAa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=bAa();
a&&a(!1,"No cast extension found")},fAa=function(){if(eAa){var a=2,b=bAa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;cAa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},gAa=function(){fAa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.B.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Md=b;this.C=(0,g.x)(this.QG,this);this.o=!1;this.u=0;this.A=this.La=null;this.B=[]},w6=function(a,b,c){g.B.call(this);
this.B=null!=c?a.bind(c):a;this.Md=b;this.A=null;this.o=!1;this.u=0;this.La=null},x6=function(a){a.La=g.dg(function(){a.La=null;
a.o&&!a.u&&(a.o=!1,x6(a))},a.Md);
var b=a.A;a.A=null;a.B.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Hza(a)},z6=function(){},A6=function(){},hAa=function(){},jAa=function(a){return(a=iAa(a))?new ActiveXObject(a):new XMLHttpRequest},iAa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},B6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.z1(this);this.u=new g.cg;this.u.setInterval(250)},lAa=function(a,b,c){a.Ql=1;
a.Xh=a6(b.clone());a.lk=c;a.F=!0;kAa(a,null)},C6=function(a,b,c,d,e){a.Ql=1;
a.Xh=a6(b.clone());a.lk=null;a.F=c;e&&(a.KD=!1);kAa(a,d)},kAa=function(a,b){a.Ll=(0,g.E)();
D6(a);a.Ti=a.Xh.clone();b6(a.Ti,"t",a.G);a.zo=0;a.bd=a.o.Lt(a.o.ko()?b:null);0<a.uu&&(a.Dr=new w6((0,g.x)(a.IE,a,a.bd),a.uu));a.B.na(a.bd,"readystatechange",a.uO);var c=a.Dj?g.Sb(a.Dj):{};a.lk?(a.xs="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.bd.send(a.Ti,a.xs,a.lk,c)):(a.xs="GET",a.KD&&!g.se&&(c.Connection="close"),a.bd.send(a.Ti,a.xs,null,c));a.o.Tf(1)},oAa=function(a,b,c){for(var d=!0;!a.jj&&a.zo<c.length;){var e=mAa(a,c);
if(e==E6){4==b&&(a.mi=4,F6(15),d=!1);break}else if(e==nAa){a.mi=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.mi=1,F6(17),d=!1);a.dg=a.dg&&d;d||(H6(a),I6(a))},mAa=function(a,b){var c=a.zo,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return nAa;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.zo=d+c;return e},qAa=function(a,b){a.Ll=(0,g.E)();
D6(a);var c=b?window.location.hostname:"";a.Ti=a.Xh.clone();$5(a.Ti,"DOMAIN",c);$5(a.Ti,"t",a.G);try{a.jg=new ActiveXObject("htmlfile")}catch(n){H6(a);a.mi=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in J6)h=J6[l];else if(l in pAa)h=J6[l]=pAa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
J6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.dd(g.dc("b/12014412"),d+"</body></html>");a.jg.open();a.jg.write(g.Zc(c));a.jg.close();a.jg.parentWindow.m=(0,g.x)(a.KN,a);a.jg.parentWindow.d=(0,g.x)(a.OC,a,!0);a.jg.parentWindow.rpcClose=(0,g.x)(a.OC,a,!1);c=a.jg.createElement("DIV");a.jg.parentWindow.document.body.appendChild(c);d=g.Ec(a.Ti.toString());d=g.ld(g.Ac(d));d=g.dd(g.dc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ed(c,d);a.o.Tf(1)},D6=function(a){a.mx=(0,g.E)()+a.C;
rAa(a,a.C)},rAa=function(a,b){if(null!=a.Xl)throw Error("WatchDog timer not null");
a.Xl=K6((0,g.x)(a.SN,a),b)},L6=function(a){a.Xl&&(g.v.clearTimeout(a.Xl),a.Xl=null)},I6=function(a){a.o.Oz()||a.jj||a.o.Wp(a)},H6=function(a){L6(a);
g.Pe(a.Dr);a.Dr=null;a.u.stop();g.hua(a.B);if(a.bd){var b=a.bd;a.bd=null;b.abort();b.dispose()}a.jg&&(a.jg=null)},G6=function(a,b){try{a.o.FC(a,b),a.o.Tf(4)}catch(c){}},tAa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;sAa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){tAa(a,b,c,d,f)},f)})}},sAa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Gza(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},uAa=function(a){this.o=a;
this.u=new z6},vAa=function(a){var b=N6(a.o,a.om,"/mail/images/cleardot.gif");
a6(b);tAa(b.toString(),5E3,(0,g.x)(a.NF,a),3,2E3);a.Tf(1)},P6=function(a){var b=a.o.M;
if(null!=b)F6(5),b?(F6(11),O6(a.o,a,!1)):(F6(12),O6(a.o,a,!0));else if(a.se=new B6(a,void 0,void 0,void 0),a.se.Dj=a.ru,b=a.o,b=N6(b,b.ko()?a.Tm:null,a.tu),F6(5),!g.qe||g.Vd(10))b6(b,"TYPE","xmlhttp"),C6(a.se,b,!1,a.Tm,!1);else{b6(b,"TYPE","html");var c=a.se;a=!!a.Tm;c.Ql=3;c.Xh=a6(b.clone());qAa(c,a)}},Q6=function(a){g.sf.call(this);
this.headers=new g.Um;this.U=a||null;this.A=!1;this.T=this.o=null;this.ga=this.M="";this.F=0;this.B="";this.C=this.ba=this.I=this.Z=!1;this.G=0;this.N=null;this.ha="";this.R=this.aa=!1},wAa=function(a){return g.qe&&g.Ud(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},xAa=function(a){return"content-type"==a.toLowerCase()},zAa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;yAa(a);R6(a)},yAa=function(a){a.Z||(a.Z=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},BAa=function(a){if(a.A&&"undefined"!=typeof g.E1)if(a.T[1]&&4==S6(a)&&2==a.getStatus())T6(a,"Local request error detected and ignored");
else if(a.I&&4==S6(a))g.dg(a.BC,0,a);else if(a.dispatchEvent("readystatechange"),4==S6(a)){T6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.vd(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!AAa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<S6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";yAa(a)}}finally{R6(a)}}},R6=function(a,b){if(a.o){CAa(a);
var c=a.o,d=a.T[0]?g.La:null;a.o=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},CAa=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.N&&(g.v.clearTimeout(a.N),a.N=null)},S6=function(a){return a.o?a.o.readyState:0},U6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},T6=function(a,b){return b+" ["+a.ga+" "+a.M+" "+a.getStatus()+"]"},V6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new z6;this.I=a||null;this.M=null!=b?b:null;this.F=c||!1},DAa=function(a,b){this.o=a;
this.map=b;this.context=null},EAa=function(a){g.Re.call(this,"statevent",a)},FAa=function(a,b){g.Re.call(this,"timingevent",a);
this.size=b},GAa=function(a){g.Re.call(this,"serverreachability",a)},JAa=function(a){HAa(a);
if(3==a.o){var b=a.En++,c=a.Fp.clone();$5(c,"SID",a.A);$5(c,"RID",b);$5(c,"TYPE","terminate");W6(a,c);b=new B6(a,a.A,b,void 0);b.Ql=2;b.Xh=a6(c.clone());Gza(new Image,b.Xh.toString());b.Ll=(0,g.E)();D6(b)}IAa(a)},KAa=function(a){a.oG(1,0);
a.Fp=N6(a,null,a.qu);X6(a)},HAa=function(a){a.ai&&(a.ai.abort(),a.ai=null);
a.Fc&&(a.Fc.cancel(),a.Fc=null);a.Zg&&(g.v.clearTimeout(a.Zg),a.Zg=null);Y6(a);a.ie&&(a.ie.cancel(),a.ie=null);a.fi&&(g.v.clearTimeout(a.fi),a.fi=null)},LAa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new DAa(a.vK++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.ie||a.fi||(a.fi=K6((0,g.x)(a.NC,a),0),a.Rk=0)},NAa=function(a,b){if(1==a.o){if(!b){a.En=Math.floor(1E5*Math.random());
var c=a.En++,d=new B6(a,"",c,void 0);d.Dj=null;var e=Z6(a),f=a.Fp.clone();$5(f,"RID",c);$5(f,"CVER","1");W6(a,f);lAa(d,f,e);a.ie=d;a.o=2}}else 3==a.o&&(b?MAa(a,b):0==a.u.length||a.ie||MAa(a))},MAa=function(a,b){if(b)if(6<a.kj){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.En-1;var d=Z6(a)}else c=b.I,d=b.lk;else c=a.En++,d=Z6(a);var e=a.Fp.clone();$5(e,"SID",a.A);$5(e,"RID",c);$5(e,"AID",a.nl);W6(a,e);c=new B6(a,a.A,c,a.Rk+1);c.Dj=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ie=c;lAa(c,e,d)},W6=function(a,b){if(a.Jd){var c=a.Jd.mz();
c&&g.Bb(c,function(d,e){$5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.kj&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.kj?e:f-d;try{g.Bb(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},OAa=function(a){a.Fc||a.Zg||(a.G=1,a.Zg=K6((0,g.x)(a.MC,a),0),a.Dk=0)},$6=function(a){if(a.Fc||a.Zg||3<=a.Dk)return!1;
a.G++;a.Zg=K6((0,g.x)(a.MC,a),PAa(a,a.Dk));a.Dk++;return!0},O6=function(a,b,c){a.us=c;
a.tg=b.qh;a.F||KAa(a)},Y6=function(a){null!=a.oj&&(g.v.clearTimeout(a.oj),a.oj=null)},PAa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Jd&&(c=null);var d=(0,g.x)(a.eP,a);c||(c=new g.Xm("//www.google.com/images/cleardot.gif"),a6(c));sAa(c.toString(),1E4,d)}else F6(2);QAa(a,b)},QAa=function(a,b){a.o=0;
a.Jd&&a.Jd.Cy(b);IAa(a);HAa(a)},IAa=function(a){a.o=0;
a.tg=-1;if(a.Jd)if(0==a.B.length&&0==a.u.length)a.Jd.At();else{g.pb(a.B);var b=g.pb(a.u);a.B.length=0;a.u.length=0;a.Jd.At(b)}},N6=function(a,b,c){var d=g.en(c);
if(""!=d.o)b&&g.Zm(d,b+"."+d.o),g.$m(d,d.B);else{var e=window.location;d=Kza(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Im&&g.Bb(a.Im,function(f,h){$5(d,h,f)});
$5(d,"VER",a.kj);W6(a,d);return d},K6=function(a,b){if(!g.Pa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},F6=function(a){b7.dispatchEvent(new EAa(b7,a))},RAa=function(){},SAa=function(){this.o=[];
this.u=[]},TAa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.B.call(this);
this.o=new g.H(this.DN,0,this);g.D(this,this.o);this.Md=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.x)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},d7=function(a,b,c){this.N=a;
this.F=b;this.A=new g.Yn;this.u=new c7(this.IO,this);this.o=null;this.Ob=!1;this.C=null;this.M="";this.I=this.B=0;this.G=[];this.R=c||!1},UAa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.us,sessionId:a.o.A,arrayId:a.o.nl}},VAa=function(a,b){a.I=b||0;
a.u.stop();a.o&&(3==a.o.o&&NAa(a.o),JAa(a.o));a.I=0},e7=function(a){return!!a.o&&3==a.o.o},WAa=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},f7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.vd(4,a))||"";b&&(this.port=":"+b);this.domain=g.wd(a)||"";a=g.Rc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.wc(a,"10.0")&&(this.u=!1))},g7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Gd(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ta(a.B,d,!0),onError:g.Ta(a.A,e),Re:g.Ta(a.C,e)};c&&(a.Fb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.vq(b,a)},$Aa=function(){var a=XAa;
YAa();i7.push(a);ZAa(i7)},j7=function(a,b){YAa();
var c=i7,d=aBa(a,String(b));g.ib(c)?bBa(d):(ZAa(c),(0,g.y)(c,function(e){e(d)}))},YAa=function(){i7||(i7=g.Ka("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",i7,void 0))},bBa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},ZAa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},aBa=function(a,b){var c=((0,g.E)()-cBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.N.call(this);
this.F=a;this.screens=[]},dBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},eBa=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.De)(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=dBa(a,b[d])||c;return c},fBa=function(a,b){var c=a.screens.length;
a.screens=(0,g.De)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},o7=function(a,b,c,d){g.N.call(this);
this.F=a;this.C=b;this.A=c;this.B=d;this.u=0;this.o=null;this.La=NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;p7(this);this.info("Initializing with "+j6(this.screens))},gBa=function(a){if(a.screens.length){var b=(0,g.Lc)(a.screens,function(d){return d.id}),c=g7(a.u,"/pairing/get_lounge_token_batch");
h7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.aH,a),(0,g.x)(a.ZG,a))}},p7=function(a){var b=Qza(Wza());
b=(0,g.De)(b,function(c){return!c.uuid});
return eBa(a,b)},r7=function(a,b){Yza((0,g.Lc)(a.screens,Oza));
b&&Xza()},t7=function(a,b){g.N.call(this);
this.F=b;var c=g.$s("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.gb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;s7("Initialized with "+g.Qk(this.o))},hBa=function(a,b,c){var d=g7(a.C,"/pairing/get_screen_availability");
h7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},u7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Ib(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Qk(a.o)),a.o=b,a.S("screenChange"));iBa(a)},v7=function(a){isNaN(a.A)||g.No(a.A);
a.A=g.Lo((0,g.x)(a.lw,a),0<a.B&&a.B<(0,g.E)()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},jBa=function(a){var b={};
(0,g.y)(a.F(),function(c){c.token?b[c.token]=c.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},iBa=function(a){a=g.Ib(g.Cb(a.o,function(b){return b}));
g.xb(a);a.length?g.Zs("yt-remote-online-screen-ids",a.join(","),60):g.at("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};kBa(this)},mBa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.Ie();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=x7(a,h);hBa(a.o,l,function(m){e(m?l:null)})}else c?lBa(a,c,(0,g.x)(function(m){var n=x7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));hBa(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},nBa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},lBa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Fb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.vq(g7(a.C,"/pairing/get_lounge_token_batch"),e)},oBa=function(a){a.screens=a.u.Ie();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},kBa=function(a){y7(a);
a.u=new q7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.hH,a));oBa(a);a.A=Qza(g.$s("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+j6(a.A));a.o=new t7(a.C,(0,g.x)(a.Ie,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Zs("yt-remote-automatic-screen-cache",(0,g.Lc)(a.A,Oza)));y7(a);a.B[b.uuid]=b.id;g.Zs("yt-remote-device-id-map",a.B,31536E3);return b},y7=function(a){a.B=g.$s("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.N.call(this);
this.T=c;this.M=a;this.o=b;this.I=null},A7=function(a,b){j7(a.T,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.u=null;this.A=0;this.C=(0,g.x)(this.KP,this);this.B=(0,g.x)(this.bO,this);this.A=g.Lo((0,g.x)(function(){pBa(this,null)},this),12E4)},qBa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Qk(void 0));
var b={type:"getMdxSessionStatus"};a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.La,(0,g.x)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Qk(b))},pBa=function(a,b){g.No(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.sr,a),d=(0,g.x)(a.Qe,a);a.Hz(b,c,d,5)}}else a.Qe(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.A=this.G=null;this.N="";this.U=c;this.B=null;this.F=g.La;this.C=NaN;this.R=(0,g.x)(this.NP,this);this.u=g.La},rBa=function(a){a.u=a.M.OE(a.N,a.o.label,a.o.friendlyName,(0,g.x)(function(b){this.u=g.La;
this.sr(b)},a),(0,g.x)(function(b){this.u=g.La;
this.Qe(b)},a))},sBa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.U;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}$za()&&(b.env_useStageMdx=1);return g.Ed(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.u=g.Lo((0,g.x)(this.ol,this,null),150)},E7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.SM,this)},tBa=function(a,b){return b?g.db(a.A,function(c){return h6(b,c.label)},a):null},F7=function(a){j7("Controller",a)},XAa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G7=function(a){return a.C||!!a.A.length||!!a.o},H7=function(a,b,c){b!=a.o&&(g.Pe(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.o):a.S("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.x)(a.KC,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.ol(null)):a.S("yt-remote-cast2-session-change",null))},uBa=function(a){var b=a.u.NE(),c=a.o&&a.o.o;
a=(0,g.Lc)(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=tBa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},ABa=function(a,b,c,d,e,f,h){vBa()?wBa(b,e,f,h)&&(J7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?xBa(a,c):(window.__onGCastApiAvailable=function(l,m){l?xBa(a,c):(K7("Failed to load cast API: "+m),L7(!1),J7(!1),g.at("yt-remote-cast-available"),g.at("yt-remote-cast-receiver"),yBa(),c(!1))},d?g.Xo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?gAa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(fAa(),t6(zBa.map(dAa))))):I7("Cannot initialize because not running Chrome")},yBa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);BBa(!1);g.To(N7);N7.length=0},O7=function(){return!!g.$s("yt-remote-cast-installed")},CBa=function(){var a=g.$s("yt-remote-cast-receiver");
return a?a.friendlyName:null},DBa=function(){I7("clearCurrentReceiver");
g.at("yt-remote-cast-receiver")},EBa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.So("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},vBa=function(){var a=0<=g.Rc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Rw||a},FBa=function(a,b){M7().init(a,b)},wBa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Zs("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){I7("onReceiverSelected: "+f.friendlyName);
g.Zs("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){I7("onReceiverResumed: "+f.friendlyName);
g.Zs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){I7("onSessionChange: "+i6(f));
f||g.at("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.Ka("yt.mdx.remote.cloudview.instance_")},xBa=function(a,b){L7(!0);
J7(!1);FBa(a,function(c){c?(BBa(!0),g.Uo("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.at("yt-remote-cast-available"),g.at("yt-remote-cast-receiver"),yBa());b(c)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.Zs("yt-remote-cast-installed",a)},P7=function(){return!!g.Ka("yt.mdx.remote.cloudview.apiReady_")},BBa=function(a){I7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.ug=!1;this.M=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.ug=!1;a.hasNext=!1;a.G=0;a.F=(0,g.E)();a.C=0;a.u=0;a.I=0;a.M=0;a.B=NaN;a.A=!1},U7=function(a){return a.sb()?((0,g.E)()-a.F)/1E3:0},V7=function(a,b){a.G=b;
a.F=(0,g.E)()},W7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.E)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Tb(a.o);b.hasPrevious=a.ug;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},$7=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.F=[];this.C=new SAa;this.A=this.u=null;this.M=(0,g.x)(this.cL,this);this.G=(0,g.x)(this.In,this);this.I=(0,g.x)(this.bL,this);this.N=(0,g.x)(this.kL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.qx,this),GBa(this))):c=3;0!=c&&(b?this.qx(c):g.Lo((0,g.x)(function(){this.qx(c)},this),0));
var d=EBa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},a8=function(a){return new S7(a.B.getPlayerContextData())},GBa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Ta(this.PM,b),this))},a)},HBa=function(a){(0,g.y)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},b8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},d8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.playerState&&(d.playerState=b);c8(a,d)},e8=function(a,b,c){a.B.sendMessage(b,c)},c8=function(a,b){HBa(a);
a.B.setPlayerContextData(Y7(b));GBa(a)},Z7=function(a,b){a.A&&(a.A.removeUpdateListener(a.M),a.A.removeMediaListener(a.G),a.In(null));
a.A=b;a.A&&(j7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.M),a.A.addMediaListener(a.G),a.A.media.length&&a.In(a.A.media[0]))},IBa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V7(d,a.u.getEstimatedTime());c8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},f8=function(a,b,c){return(0,g.x)(function(d){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),e8(this,b,c))},a)},g8=function(a,b,c){g.N.call(this);
this.C=NaN;this.R=!1;this.I=this.G=this.M=this.N=NaN;this.T=[];this.B=this.F=this.A=this.jb=this.o=null;this.Z=a;this.T.push(g.hp(window,"beforeunload",(0,g.x)(this.TG,this)));this.u=[];this.jb=new S7;this.U=b.id;this.o=JBa(this,c);this.o.subscribe("handlerOpened",this.gL,this);this.o.subscribe("handlerClosed",this.dL,this);this.o.subscribe("handlerError",this.eL,this);this.o.subscribe("handlerMessage",this.fL,this);WAa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.jb.videoId;
g.bt()&&g.Zs("yt-remote-session-video-id",d)},this)},h8=function(a){j7("conn",a)},JBa=function(a,b){return new d7(g7(a.Z,"/bc"),b)},i8=function(a,b){a.S("proxyStateChange",b)},KBa=function(a){a.C=g.Lo((0,g.x)(function(){h8("Connecting timeout");
this.Mk(1)},a),2E4)},j8=function(a){g.No(a.C);
a.C=NaN},k8=function(a){g.No(a.N);
a.N=NaN},LBa=function(a){l8(a);
a.M=g.Lo((0,g.x)(function(){m8(this,"getNowPlaying")},a),2E4)},l8=function(a){g.No(a.M);
a.M=NaN},NBa=function(a,b){b&&(j8(a),k8(a));
b==(e7(a.o)&&isNaN(a.C))?b&&(i8(a,1),m8(a,"getSubtitlesTrack")):b?(a.Fz()&&a.jb.reset(),i8(a,1),m8(a,"getNowPlaying"),MBa(a)):a.Mk(1)},OBa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jb.videoId&&(g.Pb(b.params)?a.jb.o=null:a.jb.o=b.params,a.S("remotePlayerChange"))},PBa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.jb.listId=b.params.listId||a.jb.listId;X7(a.jb,c,d);a.S("remoteQueueChange")},RBa=function(a,b){b.params=b.params||{};
PBa(a,b);QBa(a,b);a.S("autoplayDismissed")},QBa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V7(a.jb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.jb.playerState&&(c=-1E3);a.jb.playerState=c;c=Number(b.params.loadedTime);a.jb.M=isNaN(c)?0:c;c=Number(b.params.duration);a.jb.I=isNaN(c)?0:c;c=a.jb;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.jb.playerState?LBa(a):l8(a);a.S("remotePlayerChange")},SBa=function(a,b){if(-1E3!=
a.jb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jb.playerState=c;c=parseInt(b.params.currentTime,10);V7(a.jb,isNaN(c)?0:c);a.S("remotePlayerChange")}},TBa=function(a,b){var c="true"==b.params.muted;
a.jb.volume=parseInt(b.params.volume,10);a.jb.muted=c;a.S("remotePlayerChange")},UBa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},VBa=function(a,b){var c="true"==b.params.hasNext;
a.jb.ug="true"==b.params.hasPrevious;a.jb.hasNext=c;a.S("previousNextChange")},MBa=function(a){g.No(a.I);
a.I=g.Lo((0,g.x)(a.Mk,a,1),864E5)},m8=function(a,b,c){c?h8("Sending: action="+b+", params="+g.Qk(c)):h8("Sending: action="+b);
a.o.sendMessage(b,c)},n8=function(a){n7.call(this,"ScreenServiceProxy");
this.Ld=a;this.o=[];this.o.push(this.Ld.$_s("screenChange",(0,g.x)(this.IP,this)));this.o.push(this.Ld.$_s("onlineScreenChange",(0,g.x)(this.sM,this)))},$Ba=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.K("MDX_CONFIG")||b;Sza();q6();o8||(o8=new f7(b?b.loungeApiHost:void 0),$za()&&(o8.o="/api/loungedev"));p8||(p8=g.Ka("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",p8,void 0));WBa();var c=q8();if(!c){var d=new w7(o8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=q8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);ABa(a,d,function(m){m?r8()&&R7(r8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,h,l)}b&&!g.Ka("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),s8("Initializing: "+g.Qk(b)),t8.push(g.So("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),t8.push(g.So("yt-remote-cast2-receiver-selected",function(){u8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),t8.push(g.So("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),t8.push(g.So("yt-remote-cast2-session-change",XBa)),t8.push(g.So("yt-remote-connection-change",function(m){m?R7(r8(),"YouTube TV"):v8()||(R7(null,null),DBa())})),a=w8(),b.isAuto&&(a.id+="#dial"),g.Bo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(h=b.theme)&&(a.theme=h),s8(" -- with channel params: "+
g.Qk(a)),YBa(a),c.start(),r8()||ZBa())},bCa=function(){var a=aCa();
O7()&&g.$s("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},aCa=function(){var a=q8().Ld.$_gos();
var b=x8();b&&y8()&&(l6(a,b)||a.push(b));return Rza(a)},z8=function(){var a=cCa();
!a&&O7()&&CBa()&&(a={key:"cast-selector-receiver",name:CBa()});return a},cCa=function(){var a=aCa(),b=x8();
b||(b=v8());return g.db(a,function(c){return b&&h6(b,c.key)?!0:!1})},x8=function(){var a=r8();
if(!a)return null;var b=q8().Ie();return m6(b,a)},XBa=function(a){s8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=x8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&A8(),B8(a,1))}else y8()&&A8()},A8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=y8();a&&(a.disconnect(1),C8(null))},D8=function(){var a=y8();
return!!a&&3!=a.getProxyState()},s8=function(a){j7("remote",a)},q8=function(){if(!E8){var a=g.Ka("yt.mdx.remote.screenService_");
E8=a?new n8(a):null}return E8},r8=function(){return g.Ka("yt.mdx.remote.currentScreenId_")},dCa=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},eCa=function(){return g.Ka("yt.mdx.remote.connectData_")},u8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},y8=function(){return g.Ka("yt.mdx.remote.connection_")},C8=function(a){var b=y8();
u8(null);a||dCa("");g.Ia("yt.mdx.remote.connection_",a,void 0);p8&&((0,g.y)(p8,function(c){c(a)}),p8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},v8=function(){var a=g.bt();
if(!a)return null;var b=q8();if(!b)return null;b=b.Ie();return m6(b,a)},B8=function(a,b){r8();
x8()&&x8();if(F8)G8=a;else{dCa(a.id);var c=new g8(o8,a,w8());c.connect(b,eCa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){y8()&&(y8(),C8(null))});
C8(c)}},ZBa=function(){var a=v8();
a?(s8("Resume connection to: "+i6(a)),B8(a,0)):(r6(),DBa(),s8("Skipping connecting because no session screen found."))},WBa=function(){var a=w8();
if(g.Pb(a)){a=p6();var b=g.$s("yt-remote-session-name")||"",c=g.$s("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},w8=function(){return g.Ka("yt.mdx.remote.channelParams_")||{}},YBa=function(a){a?(g.Zs("yt-remote-session-app",a.app),g.Zs("yt-remote-session-name",a.name)):(g.at("yt-remote-session-app"),g.at("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},H8=function(a,b,c){g.B.call(this);
var d=this;this.module=a;this.H=b;this.Za=c;this.events=new g.ds(this);this.M=this.events.L(this.H,"onVolumeChange",this.lC);this.B=!1;this.suggestion=null;this.C=new g.hH(64);this.o=new g.H(this.UD,500,this);this.u=new g.H(this.VD,1E3,this);this.G=new v6(this.oP,0,this);this.A={};this.I=new g.H(this.yE,1E3,this);this.F=new w6(this.seekTo,1E3,this);this.N=g.La;g.D(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.SL);this.events.L(b,"captionschanged",this.aL);this.events.L(b,"captionssettingschanged",
this.XD);this.events.L(b,"videoplayerreset",this.tr);this.events.L(b,"mdxautoplaycancel",function(){d.Za.Wy()});
a=this.Za;a.ia();a.subscribe("proxyStateChange",this.EC,this);a.subscribe("remotePlayerChange",this.Pn,this);a.subscribe("remoteQueueChange",this.tr,this);a.subscribe("previousNextChange",this.AC,this);a.subscribe("nowAutoplaying",this.wC,this);a.subscribe("autoplayDismissed",this.WB,this);g.D(this,this.o);g.D(this,this.u);g.D(this,this.G);g.D(this,this.I);g.D(this,this.F);this.XD();this.tr();this.Pn()},fCa=function(a){a.Xb(0);
a.o.stop();a.Nc(new g.hH(64))},J8=function(a,b){if(I8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.Vb(c,b));a.Za.LE(a.H.getVideoData(1).videoId,c);a.A=a8(a.Za).o}},K8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.Za.playVideo(c.videoId,b,d,e,c.playerParams,c.hf,Eza(c));a.Nc(new g.hH(1))},gCa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{fA:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},I8=function(a){return a8(a.Za).videoId===a.H.getVideoData(1).videoId},L8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",W:"\u041d\u0435\u0437\u0430\u0431\u0430\u0440\u043e\u043c \u0432\u0438 \u043d\u0435 \u0437\u043c\u043e\u0436\u0435\u0442\u0435 \u043f\u0456\u0434\u043a\u043b\u044e\u0447\u0430\u0442\u0438\u0441\u044f \u0434\u043e \u0442\u0435\u043b\u0435\u0432\u0456\u0437\u043e\u0440\u0430 \u0447\u0435\u0440\u0435\u0437 \u0406\u043d\u0442\u0435\u0440\u043d\u0435\u0442 \u0437\u0430 \u0434\u043e\u043f\u043e\u043c\u043e\u0433\u043e\u044e \u043a\u043e\u0434\u0443"},
{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",X:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],W:"\u0414\u043e\u043a\u043b\u0430\u0434\u043d\u0456\u0448\u0435"},{D:"button",X:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],W:"OK"}]}]}]});this.o=new g.nO(this,250);this.learnMoreButton=this.da("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.da("ytp-mdx-manual-pairing-popup-ok");g.D(this,this.o);this.L(this.learnMoreButton,"click",this.u);this.L(this.okButton,
"click",this.A)},M8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-popup-title",W:"\u0412\u0438 \u0432\u0438\u0439\u0448\u043b\u0438 \u0437 \u043e\u0431\u043b\u0456\u043a\u043e\u0432\u043e\u0433\u043e \u0437\u0430\u043f\u0438\u0441\u0443"},{D:"div",J:"ytp-mdx-popup-description",W:"\u0412\u0456\u0434\u0435\u043e, \u044f\u043a\u0456 \u0432\u0438 \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434\u0430\u0454\u0442\u0435, \u043c\u043e\u0436\u0443\u0442\u044c \u0434\u043e\u0434\u0430\u0432\u0430\u0442\u0438\u0441\u044f \u0432 \u0456\u0441\u0442\u043e\u0440\u0456\u044e \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434\u0456\u0432 \u043d\u0430 \u0442\u0435\u043b\u0435\u0432\u0456\u0437\u043e\u0440\u0456 \u0439 \u0432\u043f\u043b\u0438\u0432\u0430\u0442\u0438 \u043d\u0430 \u0432\u0430\u0448\u0456 \u043f\u043e\u0434\u0430\u043b\u044c\u0448\u0456 \u0440\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0430\u0446\u0456\u0457. \u0429\u043e\u0431 \u0443\u043d\u0438\u043a\u043d\u0443\u0442\u0438 \u0446\u044c\u043e\u0433\u043e, \u0441\u043a\u0430\u0441\u0443\u0439\u0442\u0435 \u0434\u0456\u044e \u0442\u0430 \u0432\u0432\u0456\u0439\u0434\u0456\u0442\u044c \u043d\u0430 YouTube \u043d\u0430 \u043a\u043e\u043c\u043f\u2019\u044e\u0442\u0435\u0440\u0456."},
{D:"div",J:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",X:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"\u0421\u043a\u0430\u0441\u0443\u0432\u0430\u0442\u0438"},{D:"button",X:["ytp-button","ytp-mdx-privacy-popup-confirm"],W:"\u041f\u0456\u0434\u0442\u0432\u0435\u0440\u0434\u0438\u0442\u0438"}]}]}]});this.o=new g.nO(this,250);this.cancelButton=this.da("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.da("ytp-mdx-privacy-popup-confirm");g.D(this,this.o);this.L(this.cancelButton,"click",this.u);
this.L(this.confirmButton,"click",this.A)},N8=function(a){g.U.call(this,{D:"div",
J:"ytp-remote",K:[{D:"div",J:"ytp-remote-display-status",K:[{D:"div",J:"ytp-remote-display-status-icon",K:[g.rM()]},{D:"div",J:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.api=a;this.o=new g.nO(this,250);g.D(this,this.o);this.L(a,"presentingplayerstatechange",this.u);hCa(this,g.pM(a))},hCa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.SL("\u041f\u043e\u043c\u0438\u043b\u043a\u0430 \u043d\u0430 \u043f\u0440\u0438\u0441\u0442\u0440\u043e\u0457 $RECEIVER_NAME",c):b.sb()||g.T(b,4)?g.SL("\u0412\u0456\u0434\u0442\u0432\u043e\u0440\u044e\u0454\u0442\u044c\u0441\u044f \u043d\u0430 \u043f\u0440\u0438\u0441\u0442\u0440\u043e\u0457 $RECEIVER_NAME",c):g.SL("\u041f\u0456\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u043e \u0434\u043e \u043f\u0440\u0438\u0441\u0442\u0440\u043e\u044e $RECEIVER_NAME",c);a.ma("statustext",c);a.o.show()}else a.o.hide()},
O8=function(a,b){g.HR.call(this,"\u0412\u0456\u0434\u0442\u0432\u043e\u0440\u0438\u0442\u0438 \u043d\u0430 \u0435\u043a\u0440\u0430\u043d\u0456",0,a,b);
this.H=a;this.Si={};this.L(a,"onMdxReceiversChange",this.B);this.L(a,"presentingplayerstatechange",this.B);this.B()},P8=function(a){g.TN.call(this,a);
this.Of={key:k6(),name:"\u0426\u0435\u0439 \u043a\u043e\u043c\u043f\u2019\u044e\u0442\u0435\u0440"};this.De=null;this.subscriptions=[];this.Wv=this.Za=null;this.Si=[this.Of];this.ci=this.Of;this.Sb=new g.hH(64);this.wA=0;this.jd=-1;this.ql=null;this.Qn=this.Aq=!1;this.kk=this.Hl=null;if(!g.Hy(this.player.O())){a=this.player;var b=g.fN(a);b&&(b=b.Aj())&&(b=new O8(a,b),g.D(this,b));b=new N8(a);g.D(this,b);g.FN(a,b.element,4);this.Hl=new M8;g.D(this,this.Hl);g.FN(a,this.Hl.element,4);g.P(this.player.O().experiments,
"pair_servlet_deprecation_warning_enabled")&&(this.ql=new L8,g.D(this,this.ql),g.FN(a,this.ql.element,4));this.Qn=!!v8();this.Aq=!!g.$s("yt-remote-manual-pairing-warning-shown")}},Q8=function(a){a.kk&&(a.player.removeEventListener("presentingplayerstatechange",a.kk),a.kk=null)},iCa=function(a,b,c){a.Sb=c;
a.player.S("presentingplayerstatechange",new g.qH(c,b))},jCa=function(a,b,c){var d=!1;
1===b?d=!a.Qn:2===b&&(d=!a.Aq);d&&g.sH(c,8)&&(a.player.pauseVideo(),Q8(a))},R8=function(a,b){if(b.key!==a.ci.key)if(b.key===a.Of.key)A8();
else{if(a.ql&&!a.Aq&&b!==a.Of&&"cast-selector-receiver"!==b.key&&g.Qy(a.player.O()))kCa(a);else{var c;(c=!g.P(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.Qn||!a.Hl);(c?0:g.Qy(a.player.O())||g.Uy(a.player.O()))&&lCa(a)}a.ci=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.P(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ca(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.hf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=Eza(c))&&(d.locationInfo=c);c=d}s8("Connecting to: "+g.Qk(b));"cast-selector-receiver"==b.key?(u8(c||null),c=
c||null,P7()?M7().setLaunchParams(c):K7("setLaunchParams called before ready.")):!c&&D8()&&r8()==b.key?e6("yt-remote-connection-change",!0):(A8(),u8(c||null),c=q8().Ie(),(c=m6(c,b.key))&&B8(c,1))}},lCa=function(a){g.pM(a.player).sb()?a.player.pauseVideo():(a.kk=function(b){jCa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.kk));
a.Hl&&a.Hl.Zb();y8()||(F8=!0)},kCa=function(a){g.pM(a.player).sb()?a.player.pauseVideo():(a.kk=function(b){jCa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.kk));
a.ql&&a.ql.Zb();y8()||(F8=!0)},pAa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},J6={"'":"\\'"},mCa={},Nza={pQ:"atp",gT:"ska",QS:"que",gS:"mus",fT:"sus",oR:"dsp",YS:"seq"},s6,o6="",eAa=aAa("loadCastFramework")||aAa("loadCastApplicationFramework"),zBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Va(v6,g.B);g.k=v6.prototype;g.k.PG=function(a){this.B=arguments;this.o=!1;this.La?this.A=(0,g.E)()+this.Md:this.La=g.dg(this.C,this.Md)};
g.k.stop=function(){this.La&&(g.v.clearTimeout(this.La),this.La=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.Y=function(){this.stop();v6.wc.Y.call(this)};
g.k.QG=function(){this.A?(this.La=g.dg(this.C,this.A-(0,g.E)()),this.A=null):(this.La=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(w6,g.B);g.k=w6.prototype;g.k.KA=function(a){this.A=arguments;this.La||this.u?this.o=!0:x6(this)};
g.k.stop=function(){this.La&&(g.v.clearTimeout(this.La),this.La=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.La||(this.o=!1,x6(this))};
g.k.Y=function(){g.B.prototype.Y.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};A6.prototype.o=null;A6.prototype.getOptions=function(){var a;(a=this.o)||(a={},iAa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Va(hAa,A6);S8=new hAa;g.k=B6.prototype;g.k.Dj=null;g.k.dg=!1;g.k.Xl=null;g.k.mx=null;g.k.Ll=null;g.k.Ql=null;g.k.Xh=null;g.k.Ti=null;g.k.lk=null;g.k.bd=null;g.k.zo=0;g.k.jg=null;g.k.xs=null;g.k.mi=null;g.k.Um=-1;g.k.KD=!0;g.k.jj=!1;g.k.uu=0;g.k.Dr=null;var nAa={},E6={};g.k=B6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.uO=function(a){a=a.target;var b=this.Dr;b&&3==S6(a)?b.KA():this.IE(a)};
g.k.IE=function(a){try{if(a==this.bd)a:{var b=S6(this.bd),c=this.bd.F,d=this.bd.getStatus();if(g.qe&&!g.Vd(10)||g.se&&!g.Ud("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Fh&&!U6(this.bd))break a;this.jj||4!=b||7==c||(8==c||0>=d?this.o.Tf(3):this.o.Tf(2));L6(this);var e=this.bd.getStatus();this.Um=e;var f=U6(this.bd);(this.dg=200==e)?(4==b&&H6(this),this.F?(oAa(this,b,f),g.Fh&&this.dg&&3==b&&(this.B.na(this.u,"tick",this.oO),this.u.start())):G6(this,f),this.dg&&!this.jj&&(4==b?this.o.Wp(this):(this.dg=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.mi=3,F6(13)):(this.mi=0,F6(14)),H6(this),I6(this))}}catch(h){this.bd&&U6(this.bd)}finally{}};
g.k.oO=function(){var a=S6(this.bd),b=U6(this.bd);this.zo<b.length&&(L6(this),oAa(this,a,b),this.dg&&4!=a&&D6(this))};
g.k.KN=function(a){K6((0,g.x)(this.JN,this,a),0)};
g.k.JN=function(a){this.jj||(L6(this),G6(this,a),D6(this))};
g.k.OC=function(a){K6((0,g.x)(this.IN,this,a),0)};
g.k.IN=function(a){this.jj||(H6(this),this.dg=a,this.o.Wp(this),this.o.Tf(4))};
g.k.cancel=function(){this.jj=!0;H6(this)};
g.k.SN=function(){this.Xl=null;var a=(0,g.E)();0<=a-this.mx?(2!=this.Ql&&this.o.Tf(3),H6(this),this.mi=2,F6(18),I6(this)):rAa(this,this.mx-a)};
g.k.getLastError=function(){return this.mi};g.k=uAa.prototype;g.k.ru=null;g.k.se=null;g.k.Er=!1;g.k.Pz=null;g.k.Cp=null;g.k.Uu=null;g.k.tu=null;g.k.gf=null;g.k.qh=-1;g.k.Tm=null;g.k.om=null;g.k.connect=function(a){this.tu=a;a=N6(this.o,null,this.tu);F6(3);this.Pz=(0,g.E)();var b=this.o.I;null!=b?(this.Tm=b[0],(this.om=b[1])?(this.gf=1,vAa(this)):(this.gf=2,P6(this))):(b6(a,"MODE","init"),this.se=new B6(this,void 0,void 0,void 0),this.se.Dj=this.ru,C6(this.se,a,!1,null,!0),this.gf=0)};
g.k.NF=function(a){if(a)this.gf=2,P6(this);else{F6(4);var b=this.o;b.tg=b.ai.qh;a7(b,9)}a&&this.Tf(2)};
g.k.Lt=function(a){return this.o.Lt(a)};
g.k.abort=function(){this.se&&(this.se.cancel(),this.se=null);this.qh=-1};
g.k.Oz=function(){return!1};
g.k.FC=function(a,b){this.qh=a.Um;if(0==this.gf)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.tg=this.qh;a7(c,2);return}this.Tm=c[0];this.om=c[1]}else c=this.o,c.tg=this.qh,a7(c,2);else if(2==this.gf)if(this.Er)F6(7),this.Uu=(0,g.E)();else if("11111"==b){if(F6(6),this.Er=!0,this.Cp=(0,g.E)(),c=this.Cp-this.Pz,!g.qe||g.Vd(10)||500>c)this.qh=200,this.se.cancel(),F6(12),O6(this.o,this,!0)}else F6(8),this.Cp=this.Uu=(0,g.E)(),this.Er=!1};
g.k.Wp=function(){this.qh=this.se.Um;if(this.se.dg)0==this.gf?this.om?(this.gf=1,vAa(this)):(this.gf=2,P6(this)):2==this.gf&&((!g.qe||g.Vd(10)?!this.Er:200>this.Uu-this.Cp)?(F6(11),O6(this.o,this,!1)):(F6(12),O6(this.o,this,!0)));else{0==this.gf?F6(9):2==this.gf&&F6(10);var a=this.o;this.se.getLastError();a.tg=this.qh;a7(a,2)}};
g.k.ko=function(){return this.o.ko()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Tf=function(a){this.o.Tf(a)};g.Va(Q6,g.sf);var AAa=/^https?$/i,nCa=["POST","PUT"];g.k=Q6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.ga=b;this.Z=!1;this.A=!0;this.o=this.U?jAa(this.U):jAa(S8);this.T=this.U?this.U.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.BC,this);try{d6(T6(this,"Opening Xhr")),this.ba=!0,this.o.open(b,String(a),!0),this.ba=!1}catch(f){d6(T6(this,"Error opening Xhr: "+f.message));zAa(this,f);return}a=
c||"";var e=this.headers.clone();d&&Jza(d,function(f,h){e.set(h,f)});
d=g.db(e.df(),xAa);c=g.v.FormData&&a instanceof g.v.FormData;!g.gb(nCa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.ha&&(this.o.responseType=this.ha);"withCredentials"in this.o&&this.o.withCredentials!==this.aa&&(this.o.withCredentials=this.aa);try{CAa(this),0<this.G&&(this.R=wAa(this.o),d6(T6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Qz,this)):this.N=g.dg(this.Qz,this.G,this)),d6(T6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){d6(T6(this,"Send error: "+f.message)),zAa(this,f)}};
g.k.Qz=function(){"undefined"!=typeof g.E1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,T6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(T6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),R6(this))};
g.k.Y=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),R6(this,!0));Q6.wc.Y.call(this)};
g.k.BC=function(){this.ia()||(this.ba||this.I||this.C?BAa(this):this.RM())};
g.k.RM=function(){BAa(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<S6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=V6.prototype;g.k.Im=null;g.k.ie=null;g.k.Fc=null;g.k.qu=null;g.k.Fp=null;g.k.qy=null;g.k.Vp=null;g.k.En=0;g.k.vK=0;g.k.Jd=null;g.k.fi=null;g.k.Zg=null;g.k.oj=null;g.k.ai=null;g.k.us=null;g.k.nl=-1;g.k.vA=-1;g.k.tg=-1;g.k.Rk=0;g.k.Dk=0;g.k.kj=8;var b7=new g.sf;g.Va(EAa,g.Re);g.Va(FAa,g.Re);g.Va(GAa,g.Re);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){F6(0);this.qu=b;this.Im=c||{};d&&void 0!==e&&(this.Im.OSID=d,this.Im.OAID=e);this.F?(K6((0,g.x)(this.Jy,this,a),100),KAa(this)):this.Jy(a)};
g.k.Jy=function(a){this.ai=new uAa(this);this.ai.ru=null;this.ai.u=this.C;this.ai.connect(a)};
g.k.Oz=function(){return 0==this.o};
g.k.NC=function(a){this.fi=null;NAa(this,a)};
g.k.MC=function(){this.Zg=null;this.Fc=new B6(this,this.A,"rpc",this.G);this.Fc.Dj=null;this.Fc.uu=0;var a=this.qy.clone();$5(a,"RID","rpc");$5(a,"SID",this.A);$5(a,"CI",this.us?"0":"1");$5(a,"AID",this.nl);W6(this,a);if(!g.qe||g.Vd(10))$5(a,"TYPE","xmlhttp"),C6(this.Fc,a,!0,this.Vp,!1);else{$5(a,"TYPE","html");var b=this.Fc,c=!!this.Vp;b.Ql=3;b.Xh=a6(a.clone());qAa(b,c)}};
g.k.FC=function(a,b){if(0!=this.o&&(this.Fc==a||this.ie==a))if(this.tg=a.Um,this.ie==a&&3==this.o)if(7<this.kj){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Zg){if(this.Fc)if(this.Fc.Ll+3E3<this.ie.Ll)Y6(this),this.Fc.cancel(),this.Fc=null;else break a;$6(this);F6(19)}}else this.vA=c[1],0<this.vA-this.nl&&37500>c[2]&&this.us&&0==this.Dk&&!this.oj&&(this.oj=K6((0,g.x)(this.WK,this),6E3));else a7(this,11)}else b!=mCa.NQ.o&&a7(this,11);else if(this.Fc==
a&&Y6(this),!g.lc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.nl=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Vp=e[2],e=e[3],null!=e?this.kj=e:this.kj=6,this.o=3,this.Jd&&this.Jd.Ey(),this.qy=N6(this,this.ko()?this.Vp:null,this.qu),OAa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Jd&&this.Jd.Dy(e),this.Dk=0)}}};
g.k.WK=function(){null!=this.oj&&(this.oj=null,this.Fc.cancel(),this.Fc=null,$6(this),F6(20))};
g.k.Wp=function(a){if(this.Fc==a){Y6(this);this.Fc=null;var b=2}else if(this.ie==a)this.ie=null,b=1;else return;this.tg=a.Um;if(0!=this.o)if(a.dg)1==b?(b=(0,g.E)()-a.Ll,b7.dispatchEvent(new FAa(b7,a.lk?a.lk.length:0,b,this.Rk)),X6(this),this.B.length=0):OAa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.tg)){if(d=1==b)this.ie||this.fi||1==this.o||2<=this.Rk?d=!1:(this.fi=K6((0,g.x)(this.NC,this,a),PAa(this,this.Rk)),this.Rk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.oG=function(a){if(!g.gb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.eP=function(a){a?F6(2):(F6(1),QAa(this,8))};
g.k.Lt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Q6;a.aa=!1;return a};
g.k.isActive=function(){return!!this.Jd&&this.Jd.isActive(this)};
g.k.Tf=function(a){b7.dispatchEvent(new GAa(b7,a))};
g.k.ko=function(){return!(!g.qe||g.Vd(10))};
g.k=RAa.prototype;g.k.Ey=function(){};
g.k.Dy=function(){};
g.k.Cy=function(){};
g.k.At=function(){};
g.k.mz=function(){return{}};
g.k.isActive=function(){return!0};g.k=SAa.prototype;g.k.isEmpty=function(){return g.ib(this.o)&&g.ib(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.gb(this.o,a)||g.gb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.mua)(b,a);0<=c?(g.kb(b,c),b=!0):b=!1;return b||g.lb(this.u,a)};
g.k.Ud=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Va(c7,g.B);g.k=c7.prototype;g.k.DN=function(){this.Md=Math.min(3E5,2*this.Md);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Md+15E3*Math.random();this.o.kb(a);this.u=(0,g.E)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Md=5E3};g.Va(d7,RAa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Ji=function(a){return this.A.Ej(a)};
g.k.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.k.dispose=function(){this.Ob||(this.Ob=!0,g.Pe(this.A),VAa(this),g.Pe(this.u),this.u=null)};
g.k.ia=function(){return this.Ob};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.R),e=this.o;e&&(e.Jd=null);d.Jd=this;this.o=d;e?this.o.connect(a,b,this.F,e.A,e.nl):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Vb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):e7(this)&&LAa(this.o,c)};
g.k.Ey=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)LAa(this.o,a[b])}this.S("handlerOpened")};
g.k.Cy=function(a){var b=2==a&&401==this.o.tg;4==a||b||this.u.start();this.S("handlerError",a)};
g.k.At=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.mz=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.Vb(a,this.C);return a};
g.k.Dy=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),JAa(this.o)):this.S("handlerMessage",new TAa(a[0],a[1]))};
g.k.IO=function(){this.u.isActive();var a=this.o,b=0;a.Fc&&b++;a.ie&&b++;0==b&&this.connect(this.C,this.B)};f7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.C=function(a){a(Error("request timed out"))};var cBa=(0,g.E)(),i7=null,l7=Array(50),k7=-1,m7=!1;g.Va(n7,g.N);n7.prototype.Ie=function(){return this.screens};
n7.prototype.contains=function(a){return!!l6(this.screens,a)};
n7.prototype.get=function(a){return a?m6(this.screens,a):null};
n7.prototype.info=function(a){j7(this.F,a)};g.t(o7,g.N);g.k=o7.prototype;g.k.start=function(){!this.o&&isNaN(this.La)&&this.ME()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.La)||(g.No(this.La),this.La=NaN)};
g.k.Y=function(){this.stop();g.N.prototype.Y.call(this)};
g.k.ME=function(){this.La=NaN;this.o=g.vq(g7(this.F,"/pairing/get_screen"),{method:"POST",Fb:{pairing_code:this.C},timeout:5E3,onSuccess:(0,g.x)(this.GP,this),onError:(0,g.x)(this.FP,this),Re:(0,g.x)(this.HP,this)})};
g.k.GP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.S("pairingComplete",new g6(c))};
g.k.FP=function(a){this.o=null;a.status&&404==a.status?this.u>=oCa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=oCa[this.u],this.La=g.Lo((0,g.x)(this.ME,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.HP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var oCa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Va(q7,n7);g.k=q7.prototype;g.k.start=function(){p7(this)&&this.S("screenChange");!g.$s("yt-remote-lounge-token-expiration")&&gBa(this);g.No(this.o);this.o=g.Lo((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){p7(this);dBa(this,a);r7(this,!1);this.S("screenChange");b(a);a.token||gBa(this)};
g.k.remove=function(a,b){var c=p7(this);fBa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.rs=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.Y=function(){g.No(this.o);q7.wc.Y.call(this)};
g.k.aH=function(a){p7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.F,"Missed "+b+" lounge tokens.")};
g.k.ZG=function(a){j7(this.F,"Requesting lounge tokens failed: "+a)};g.t(t7,g.N);g.k=t7.prototype;g.k.start=function(){var a=parseInt(g.$s("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.E)()-144E5<a?0:a)?v7(this):(this.B=(0,g.E)()+3E5,g.Zs("yt-remote-fast-check-period",this.B),this.lw())};
g.k.isEmpty=function(){return g.Pb(this.o)};
g.k.update=function(){s7("Updating availability on schedule.");var a=this.F(),b=g.Cb(this.o,function(c,d){return c&&!!m6(a,d)},this);
u7(this,b)};
g.k.Y=function(){g.No(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.Y.call(this)};
g.k.lw=function(){g.No(this.A);this.A=NaN;this.u&&this.u.abort();var a=jBa(this);if(c6(a)){var b=g7(this.C,"/pairing/get_screen_availability");this.u=h7(this.C,b,{lounge_token:g.Ib(a).join(",")},(0,g.x)(this.nN,this,a),(0,g.x)(this.mN,this))}else u7(this,{}),v7(this)};
g.k.nN=function(a,b){this.u=null;var c=g.Ib(jBa(this));if(g.yb(c,g.Ib(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.sc("Changing Screen set during request."),this.lw()};
g.k.mN=function(a){this.sc("Screen availability failed: "+a);this.u=null;v7(this)};
g.k.sc=function(a){j7("OnlineScreenService",a)};g.Va(w7,n7);g.k=w7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.rs=function(a,b,c,d){this.u.contains(a)?this.u.rs(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.F,a),d(Error(a)))};
g.k.Ie=function(a){return a?this.screens:g.ob(this.screens,(0,g.De)(this.A,function(b){return!this.contains(b)},this))};
g.k.NE=function(){return(0,g.De)(this.Ie(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.OE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Pe(f);d(x7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Pe(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.JP=function(a,b,c,d){g.vq(g7(this.C,"/pairing/get_screen"),{method:"POST",Fb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new g6(f.screen||{});if(!h.name||nBa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);nBa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(x7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Re:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.Y=function(){g.Pe(this.u);g.Pe(this.o);w7.wc.Y.call(this)};
g.k.hH=function(){oBa(this);this.S("screenChange");this.o.update()};
w7.prototype.dispose=w7.prototype.dispose;g.Va(z7,g.N);g.k=z7.prototype;g.k.getScreen=function(){return this.I};
g.k.sr=function(a){this.I=a;this.S("sessionScreen",this.I)};
g.k.Qe=function(a){this.ia()||(a&&A7(this,""+a),this.I=null,this.S("sessionScreen",null))};
g.k.info=function(a){j7(this.T,a)};
g.k.QE=function(){return null};
g.k.xw=function(a){var b=this.o;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.Y=function(){this.xw("");z7.wc.Y.call(this)};g.t(B7,z7);g.k=B7.prototype;g.k.ww=function(a){if(this.u){if(this.u==a)return;A7(this,"Overriding cast sesison with new session object");this.u.removeUpdateListener(this.C);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.u=a;this.u.addUpdateListener(this.C);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);qBa(this)};
g.k.ol=function(a){this.info("launchWithParams no-op for Cast: "+g.Qk(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.x)(function(){this.Qe()},this),(0,g.x)(function(){this.Qe(Error("Failed to stop receiver app."))},this)):this.Qe(Error("Stopping cast device witout session."))};
g.k.xw=function(){};
g.k.Y=function(){this.info("disposeInternal");g.No(this.A);this.A=0;this.u&&(this.u.removeUpdateListener(this.C),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.u=null;z7.prototype.Y.call(this)};
g.k.bO=function(a,b){if(!this.ia())if(b){var c=y6(b);if(g.Qa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Qk(c));switch(d){case "mdxSessionStatus":pBa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.k.Hz=function(a,b,c,d){mBa(this.M,this.o.label,a,this.o.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Lo((0,g.x)(this.Hz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.QE=function(){return this.u};
g.k.KP=function(a){this.ia()||a||(A7(this,"Cast session died."),this.Qe())};g.t(C7,z7);g.k=C7.prototype;g.k.ww=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.k.ol=function(a){this.B=a;this.F()};
g.k.stop=function(){this.u();this.u=g.La;g.No(this.C);this.A?this.A.stop((0,g.x)(this.Qe,this,null),(0,g.x)(this.Qe,this,"Failed to stop DIAL device.")):this.Qe()};
g.k.Y=function(){this.u();this.u=g.La;g.No(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;z7.prototype.Y.call(this)};
g.k.NP=function(a){this.ia()||a||(A7(this,"DIAL session died."),this.u(),this.u=g.La,this.Qe())};
g.k.Eu=function(a){this.N=k6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,sBa(this));a(b);rBa(this)}else this.F=(0,g.x)(function(){g.No(this.C);this.F=g.La;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,sBa(this));a(c);rBa(this)},this),this.C=g.Lo((0,g.x)(function(){this.F()},this),100)};
g.k.xH=function(a,b,c){mBa(this.M,this.G.receiver.label,a,this.o.friendlyName,(0,g.x)(function(d){d&&d.token?(this.sr(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Eu(b,c)},this),(0,g.x)(function(d){A7(this,"Failed to get DIAL screen: "+d);
this.Eu(b,c)},this))};g.t(D7,z7);D7.prototype.stop=function(){this.Qe()};
D7.prototype.ww=function(){};
D7.prototype.ol=function(){g.No(this.u);this.u=NaN;var a=m6(this.M.Ie(),this.o.label);a?this.sr(a):this.Qe(Error("No such screen"))};
D7.prototype.Y=function(){g.No(this.u);this.u=NaN;z7.prototype.Y.call(this)};g.t(E7,g.N);g.k=E7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.WM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.IC,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.rL,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ia()||
(chrome.cast.addReceiverActionListener(this.B),$Aa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.PE,this)),this.A=uBa(this),chrome.cast.setCustomReceivers(this.A,g.La,(0,g.x)(function(h){this.sc("Failed to set initial custom receivers: "+g.Qk(h))},this)),this.S("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.x)(function(h){this.sc("Failed to initialize API: "+g.Qk(h));
b(!1)},this))};
g.k.PO=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.o.o.friendlyName),H7(this,null)}if(a&&b){if(!this.o){c=m6(this.u.Ie(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=tBa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.La,(0,g.x)(function(e){this.sc("Failed to set initial custom receivers: "+g.Qk(e))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.u,d),!0)}this.o.xw(b)}else F7("setConnectedScreenStatus: no screen.")};
g.k.QO=function(a){this.ia()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.ol(a):this.sc("Setting connection data without a session")};
g.k.MP=function(){this.ia()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.IC,this),(0,g.x)(this.qN,this))};
g.k.Y=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.PE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=XAa,b=g.Ka("yt.mdx.remote.debug.handlers_");g.lb(b||[],a);g.Pe(this.o);g.N.prototype.Y.call(this)};
g.k.sc=function(a){j7("Controller",a)};
g.k.KC=function(a,b){this.o==a&&(b||H7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.SM=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.o.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.o.o.friendlyName),this.o.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:H7(this,new B7(this.u,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.o.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.k.rL=function(a){if(this.ia())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.o:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return F7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.xH,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Eu,b))};
g.k.IC=function(a){if(!this.ia()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.u,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.o,d=m6(this.u.Ie(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Pe(this.o),this.o=new B7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.KC,this,this.o)),this.o.ol(null));this.o.ww(a)}}};
g.k.LP=function(){return this.o?this.o.QE():null};
g.k.qN=function(a){this.ia()||(this.sc("Failed to estabilish a session: "+g.Qk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.k.WM=function(a){F7("Receiver availability updated: "+a);if(!this.ia()){var b=G7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.S("yt-remote-cast2-availability-change",G7(this))}};
g.k.PE=function(){this.ia()||(this.A=uBa(this),F7("Updating custom receivers: "+g.Qk(this.A)),chrome.cast.setCustomReceivers(this.A,g.La,(0,g.x)(function(){this.sc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.QO;E7.prototype.setConnectedScreenStatus=E7.prototype.PO;E7.prototype.stopSession=E7.prototype.MP;E7.prototype.getCastSession=E7.prototype.LP;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.k=S7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.ug=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.sb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+U7(this):this.I};
g.k.clone=function(){return new S7(Y7(this))};g.t($7,g.N);g.k=$7.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.La,f8(this,"play")):e8(this,"play"),d8(this,1,W7(a8(this))),this.S("remotePlayerChange")):b8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.La,f8(this,"pause")):e8(this,"pause"),d8(this,2,W7(a8(this))),this.S("remotePlayerChange")):b8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=a8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.sb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.La,f8(this,"seekTo",{newTime:a}))}else e8(this,"seekTo",{newTime:a});d8(this,3,a);this.S("remotePlayerChange")}else b8(this,g.Ta(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.La,f8(this,"stopVideo")):e8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);c8(this,a);this.S("remotePlayerChange")}else b8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=a8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);e8(this,"setVolume",e)}c.muted=b;c.volume=a;c8(this,c)}else b8(this,g.Ta(this.setVolume,a,b))};
g.k.LE=function(a,b){if(1==this.o){var c=a8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Qk(b.style),g.Vb(d,c.o));e8(this,"setSubtitlesTrack",d);c8(this,c)}else b8(this,g.Ta(this.LE,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();e8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=a8(this);d.audioTrackId=c;c8(this,d)}else b8(this,g.Ta(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=a8(this);c=c||0;var m={videoId:a,currentIndex:c};X7(l,a,c);void 0!==b&&(V7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Qk(h));e8(this,"setPlaylist",m);d||c8(this,l)};
g.k.zr=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"previous")}else b8(this,g.Ta(this.zr,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"next")}else b8(this,g.Ta(this.nextVideo,a,b))};
g.k.Wy=function(){1==this.o?e8(this,"dismissAutoplay"):b8(this,this.Wy)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.k.Y=function(){HBa(this);this.B=null;this.C.clear();Z7(this,null);g.N.prototype.Y.call(this)};
g.k.qx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.ib(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.PM=function(a,b){this.S(a,b)};
g.k.cL=function(a){if(!a)this.In(null),Z7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c8(this,b)}};
g.k.In=function(a){j7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),IBa(this),this.S("remotePlayerChange")};
g.k.bL=function(a){a?(IBa(this),this.S("remotePlayerChange")):this.In(null)};
g.k.Qw=function(){e8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.kL=function(){var a=EBa();a&&Z7(this,a)};
g.k.sc=function(a){j7("CP",a)};g.t(g8,g.N);g.k=g8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.jb.listId=c);this.jb.videoId=d;this.jb.index=h||0;this.jb.state=3;V7(this.jb,m);this.B="UNSUPPORTED";h8("Connecting with setPlaylist and params: "+g.Qk(l));this.o.connect({method:"setPlaylist",
params:g.Qk(l)},a,Vza())}else h8("Connecting without params"),this.o.connect({},a,Vza());KBa(this)};
g.k.dispose=function(){this.ia()||(this.S("beforeDispose"),i8(this,3));g.N.prototype.dispose.call(this)};
g.k.Y=function(){j8(this);l8(this);k8(this);g.No(this.G);this.G=NaN;g.No(this.I);this.I=NaN;this.A=null;g.ip(this.T);this.T.length=0;this.o.dispose();g.N.prototype.Y.call(this);this.B=this.F=this.u=this.jb=this.o=null};
g.k.TG=function(){this.Mk(2)};
g.k.gL=function(){h8("Channel opened");this.R&&(this.R=!1,k8(this),this.N=g.Lo((0,g.x)(function(){h8("Timing out waiting for a screen.");this.Mk(1)},this),15E3));
Zza(UAa(this.o),this.U)};
g.k.dL=function(){h8("Channel closed");isNaN(this.C)?r6(!0):r6();this.dispose()};
g.k.eL=function(a){r6();isNaN(this.Pm())?(h8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,h8("Channel error: "+a+" with reconnection in "+this.Pm()+" ms"),i8(this,2))};
g.k.fL=function(a){a.params?h8("Received: action="+a.action+", params="+g.Qk(a.params)):h8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.u=(0,g.Lc)(a,function(c){return new f6(c)});
a=!!g.db(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
NBa(this,a);break;case "loungeScreenDisconnected":g.nb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
NBa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.db(this.u,function(c){return b?c.id==b.id:!1})||Fza(this.u,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.nb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":PBa(this,a);break;case "nowPlaying":RBa(this,a);break;case "onStateChange":QBa(this,a);break;case "onAdStateChange":SBa(this,a);break;case "onVolumeChanged":TBa(this,a);break;case "onSubtitlesTrackChanged":OBa(this,a);break;case "nowAutoplaying":UBa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":VBa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:h8("Unrecognized action: "+a.action)}};
g.k.EO=function(){if(this.A){var a=this.A;this.A=null;this.jb.videoId!=a&&m8(this,"getNowPlaying")}};
g.k.JG=function(){var a=3;this.ia()||(a=0,isNaN(this.Pm())?e7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Mk=function(a){h8("Disconnecting with "+a);j8(this);this.S("beforeDisconnect",a);1==a&&r6();VAa(this.o,a);this.dispose()};
g.k.HG=function(){var a=this.jb;this.A&&(a=this.jb.clone(),X7(a,this.A,a.index));return Y7(a)};
g.k.RO=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.jb.videoId&&(this.A=b.videoId,g.No(this.G),this.G=g.Lo((0,g.x)(this.EO,this),5E3));var c=[];this.jb.listId==b.listId&&this.jb.videoId==b.videoId&&this.jb.index==b.index||c.push("remoteQueueChange");this.jb.playerState==b.playerState&&this.jb.volume==b.volume&&this.jb.muted==b.muted&&W7(this.jb)==W7(b)&&g.Qk(this.jb.o)==g.Qk(b.o)||c.push("remotePlayerChange");this.jb.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.k.Fz=function(){var a=this.o.F.id,b=g.db(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Pm=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.E)():NaN};
g.k.wG=function(){return this.B||"UNSUPPORTED"};
g.k.xG=function(){return this.F||""};
g.k.EP=function(){if(!isNaN(this.Pm())){var a=this.o.u;g.Cn(a.o);a.start()}};
g.k.MO=function(a,b){m8(this,a,b);MBa(this)};
g8.prototype.subscribe=g8.prototype.subscribe;g8.prototype.unsubscribeByKey=g8.prototype.Ji;g8.prototype.getProxyState=g8.prototype.JG;g8.prototype.disconnect=g8.prototype.Mk;g8.prototype.getPlayerContextData=g8.prototype.HG;g8.prototype.setPlayerContextData=g8.prototype.RO;g8.prototype.getOtherConnectedRemoteId=g8.prototype.Fz;g8.prototype.getReconnectTimeout=g8.prototype.Pm;g8.prototype.getAutoplayMode=g8.prototype.wG;g8.prototype.getAutoplayVideoId=g8.prototype.xG;g8.prototype.reconnect=g8.prototype.EP;
g8.prototype.sendMessage=g8.prototype.MO;g.t(n8,n7);g.k=n8.prototype;g.k.Ie=function(a){return this.Ld.$_gs(a)};
g.k.contains=function(a){return!!this.Ld.$_c(a)};
g.k.get=function(a){return this.Ld.$_g(a)};
g.k.start=function(){this.Ld.$_st()};
g.k.add=function(a,b,c){this.Ld.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ld.$_r(a,b,c)};
g.k.rs=function(a,b,c,d){this.Ld.$_un(a,b,c,d)};
g.k.Y=function(){for(var a=0,b=this.o.length;a<b;++a)this.Ld.$_ubk(this.o[a]);this.o.length=0;this.Ld=null;n7.prototype.Y.call(this)};
g.k.IP=function(){this.S("screenChange")};
g.k.sM=function(){this.S("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.JP;w7.prototype.$_gsppc=w7.prototype.OE;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.rs;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.Ie;w7.prototype.$_gos=w7.prototype.NE;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.Ji;var G8=null,F8=!1,o8=null,p8=null,E8=null,t8=[];g.t(H8,g.B);g.k=H8.prototype;g.k.Y=function(){g.B.prototype.Y.call(this);this.o.stop();this.u.stop();this.G.stop();this.N();var a=this.Za;a.unsubscribe("proxyStateChange",this.EC,this);a.unsubscribe("remotePlayerChange",this.Pn,this);a.unsubscribe("remoteQueueChange",this.tr,this);a.unsubscribe("previousNextChange",this.AC,this);a.unsubscribe("nowAutoplaying",this.wC,this);a.unsubscribe("autoplayDismissed",this.WB,this);this.Za=this.module=null};
g.k.aB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Za.o)if(I8(this)){if(!a8(this.Za).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":a8(this.Za).sb()?this.Za.pause():this.Za.play();break;case "control_play":this.Za.play();break;case "control_pause":this.Za.pause();break;case "control_seek":this.F.KA(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();K8(this,0===c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.aL=function(a){this.G.PG(a)};
g.k.oP=function(a){this.aB("control_subtitles_set_track",g.Pb(a)?null:a)};
g.k.XD=function(){var a=this.H.getOption("captions","track");g.Pb(a)||J8(this,a)};
g.k.Xb=function(a){this.module.Xb(a,this.H.getVideoData().lengthSeconds)};
g.k.lC=function(a){if(I8(this)){this.Za.unsubscribe("remotePlayerChange",this.Pn,this);var b=Math.round(a.volume);a=!!a.muted;var c=a8(this.Za);if(b!==c.volume||a!==c.muted)this.Za.setVolume(b,a),this.I.start();this.Za.subscribe("remotePlayerChange",this.Pn,this)}};
g.k.SL=function(){g.Pb(this.A)||gCa(this,this.A);this.B=!1};
g.k.EC=function(a,b){this.u.stop();2===b&&this.VD()};
g.k.Pn=function(){if(I8(this)){this.o.stop();var a=a8(this.Za);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.jd=1;break;case 1082:case 1083:this.module.jd=0;break;default:this.module.jd=-1}switch(a.playerState){case 1081:case 1:this.Nc(new g.hH(8));this.UD();break;case 1085:case 3:this.Nc(new g.hH(9));break;case 1083:case 0:this.Nc(new g.hH(2));this.F.stop();this.Xb(this.H.getVideoData().lengthSeconds);break;case 1084:this.Nc(new g.hH(4));break;case 2:this.Nc(new g.hH(4));
this.Xb(W7(a));break;case -1:this.Nc(new g.hH(64));break;case -1E3:this.Nc(new g.hH(128,{errorCode:"mdx.remoteerror",errorMessage:"\u0426\u0435 \u0432\u0456\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u0435 \u0434\u043b\u044f \u0432\u0456\u0434\u0434\u0430\u043b\u0435\u043d\u043e\u0433\u043e \u0432\u0456\u0434\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f."}))}a=a8(this.Za).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==
b.languageName&&a.kind==b.kind:1)||(this.A=a,gCa(this,a));a=a8(this.Za);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.yE()}else fCa(this)};
g.k.AC=function(){this.H.S("mdxpreviousnextchange")};
g.k.tr=function(){I8(this)||fCa(this)};
g.k.wC=function(a){isNaN(a)||this.H.S("mdxnowautoplaying",a)};
g.k.WB=function(){this.H.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){I8(this)&&this.Za.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a8(this.Za).playerState?K8(this,a):b&&this.Za.seekTo(a)};
g.k.yE=function(){if(I8(this)){var a=a8(this.Za);this.events.ob(this.M);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.M=this.events.L(this.H,"onVolumeChange",this.lC)}};
g.k.UD=function(){this.o.stop();if(!this.Za.ia()){var a=a8(this.Za);a.sb()&&this.Nc(new g.hH(8));this.Xb(W7(a));this.o.start()}};
g.k.VD=function(){this.u.stop();this.o.stop();var a=this.Za.B.getReconnectTimeout();2==this.Za.o&&!isNaN(a)&&this.u.start()};
g.k.Nc=function(a){this.u.stop();var b=this.C;if(!g.mH(b,a)){var c=g.T(a,2);c!==g.T(this.C,2)&&g.ZT(this.H.app,c);this.C=a;iCa(this.module,b,a)}};g.t(L8,g.U);L8.prototype.Zb=function(){this.o.show()};
L8.prototype.Sa=function(){this.o.hide()};
L8.prototype.u=function(){g.uO("https://support.google.com/youtube/answer/7640706")};
L8.prototype.A=function(){e6("mdx-manual-pairing-popup-ok");this.Sa()};g.t(M8,g.U);M8.prototype.Zb=function(){this.o.show()};
M8.prototype.Sa=function(){this.o.hide()};
M8.prototype.u=function(){e6("mdx-privacy-popup-cancel");this.Sa()};
M8.prototype.A=function(){e6("mdx-privacy-popup-confirm");this.Sa()};g.t(N8,g.U);N8.prototype.u=function(a){hCa(this,a.state)};g.t(O8,g.HR);O8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.Si=g.Ab(a,this.o,this),g.JR(this,(0,g.Lc)(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Mb(this.o(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.o=function(a){return a.key};
O8.prototype.Rf=function(a){return"cast-selector-receiver"===a?"\u0422\u0440\u0430\u043d\u0441\u043b\u044e\u0432\u0430\u0442\u0438 \u0447\u0435\u0440\u0435\u0437\u2026":this.Si[a].name};
O8.prototype.xd=function(a){g.HR.prototype.xd.call(this,a);this.H.setOption("remote","currentReceiver",this.Si[a]);this.Na.Sa()};g.t(P8,g.TN);g.k=P8.prototype;
g.k.create=function(){$Ba(g.wy(this.player.O()));this.subscriptions.push(g.So("yt-remote-before-disconnect",this.YK,this));this.subscriptions.push(g.So("yt-remote-connection-change",this.XM,this));this.subscriptions.push(g.So("yt-remote-receiver-availability-change",this.CC,this));this.subscriptions.push(g.So("yt-remote-auto-connect",this.VM,this));this.subscriptions.push(g.So("yt-remote-receiver-resumed",this.UM,this));this.subscriptions.push(g.So("mdx-privacy-popup-confirm",this.sO,this));this.subscriptions.push(g.So("mdx-privacy-popup-cancel",
this.rO,this));this.subscriptions.push(g.So("mdx-manual-pairing-popup-ok",this.QH,this));this.CC()};
g.k.load=function(){this.player.cancelPlayback();g.TN.prototype.load.call(this);this.De=new H8(this,this.player,this.Za);var a=(a=eCa())?a.currentTime:0;var b=D8()?new $7(y8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!==a&&this.Xb(a);iCa(this,this.Sb,this.Sb);g.fU(this.player.app,6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.ci=this.Of;g.Qe(this.De,this.Za);this.Za=this.De=null;g.TN.prototype.unload.call(this);g.fU(this.player.app,5);Q8(this)};
g.k.Y=function(){g.To(this.subscriptions);g.TN.prototype.Y.call(this)};
g.k.Ig=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.De.aB.apply(this.De,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.jd};
g.k.LG=function(){return this.loaded?this.De.suggestion:null};
g.k.ug=function(){return this.Za?a8(this.Za).ug:!1};
g.k.hasNext=function(){return this.Za?a8(this.Za).hasNext:!1};
g.k.Xb=function(a,b){this.wA=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.wA};
g.k.getProgressState=function(){var a=a8(this.Za),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.hd():!a.isAdPlaying()&&this.player.hd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+U7(a):a.B,isAtLiveHead:1>=(a.A?a.u+U7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+U7(a):a.u,seekableStart:0<a.C?a.C+
U7(a):a.C}};
g.k.nextVideo=function(){this.Za&&this.Za.nextVideo()};
g.k.zr=function(){this.Za&&this.Za.zr()};
g.k.YK=function(a){1===a&&(this.Wv=this.Za?a8(this.Za):null)};
g.k.XM=function(){var a=D8()?new $7(y8(),void 0):null;if(a){var b=this.ci;this.loaded&&this.unload();this.Za=a;this.Wv=null;b.key!==this.Of.key&&(this.ci=b,this.load())}else g.Pe(this.Za),this.Za=null,this.loaded&&(this.unload(),(a=this.Wv)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.CC=function(){this.Si=[this.Of].concat(bCa());var a=z8()||this.Of;R8(this,a);this.player.ra("onMdxReceiversChange")};
g.k.VM=function(){var a=z8();R8(this,a)};
g.k.UM=function(){this.ci=z8()};
g.k.sO=function(){this.Qn=!0;Q8(this);F8=!1;G8&&B8(G8,1);G8=null};
g.k.rO=function(){this.Qn=!1;Q8(this);R8(this,this.Of);this.ci=this.Of;F8=!1;G8=null;this.player.playVideo()};
g.k.QH=function(){this.Aq=!0;Q8(this);g.Zs("yt-remote-manual-pairing-warning-shown",!0,2592E3);F8=!1;G8&&B8(G8,1);G8=null};
g.k.cd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Si;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q7():R8(this,b)),this.loaded?this.ci:this.Of;case "quickCast":return 2===this.Si.length&&"cast-selector-receiver"===this.Si[1].key?(b&&Q7(),!0):!1}};
g.k.Qw=function(){this.Za.Qw()};
g.k.ag=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.dO.remote=P8;})(_yt_player);
